import { test, expect } from '@playwright/test';
test('company routes, navigation and interactive journey work on every screen',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 for(const route of ['/about','/client-journey','/customization-brief']){
  await page.goto(route);await expect(page.locator('main h1')).toBeVisible();await expect(page).toHaveTitle(/JD Jackets/);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBe(false);
  if(route==='/about'){await expect(page.locator('.ecosystem-card')).toHaveCount(6);await expect(page.locator('.principles-grid article')).toHaveCount(8);for(const img of await page.locator('.company-jacket-pair img').all())await expect.poll(()=>img.evaluate(i=>(i as HTMLImageElement).naturalWidth)).toBeGreaterThan(0)}
  if(route==='/client-journey'){
   await expect(page.getByRole('tab')).toHaveCount(11);await page.getByRole('tab',{name:'06 Sample & approve'}).click();await expect(page.getByRole('tabpanel')).toContainText('final approval before bulk production');
   await page.getByRole('tab',{name:'06 Sample & approve'}).press('End');await expect(page.getByRole('tab',{name:'11 Reorder & partnership'})).toBeFocused();await expect(page.getByRole('tabpanel')).toContainText('approved specifications');
  }
  await page.screenshot({path:`test-results/${test.info().project.name}-${route.slice(1)}.png`,fullPage:true});
 }
 if(test.info().project.name==='mobile'){await page.getByRole('button',{name:'Open navigation'}).click();await page.getByRole('navigation',{name:'Main navigation'}).getByRole('link',{name:'About us',exact:true}).click();await expect(page).toHaveURL(/\/about$/)}
 expect(errors).toEqual([]);
});
test('complete customization brief preserves all selections through review, edit and download',async({page})=>{
 await page.goto('/customization-brief');await page.getByLabel('Organisation / company *',{exact:true}).fill('Example Company');await page.getByLabel('Contact person *',{exact:true}).fill('Test Customer');await page.getByLabel('Phone number *',{exact:true}).fill('+26771000000');await page.getByLabel('Project objective / purpose *',{exact:true}).fill('Professional jackets for our field team');await page.getByLabel('Quantity required (total units) *',{exact:true}).fill('25');
 await page.getByLabel('Trimmed',{exact:true}).check();await page.getByLabel('Logo',{exact:true}).check();await page.getByLabel('Left chest',{exact:true}).check();await page.getByLabel('Brand colours (up to four; codes if known)',{exact:true}).fill('Navy and gold');await page.getByLabel('Preferred collection',{exact:true}).selectOption({label:'Corporate Pro'});await page.getByLabel('Windproof',{exact:true}).check();await page.getByLabel('Removable hood',{exact:true}).check();await page.getByLabel('I require a physical sample',{exact:true}).check();await page.getByLabel('Approval authority — who signs off?',{exact:true}).fill('Procurement lead');await page.getByLabel('WhatsApp',{exact:true}).check();await page.getByLabel('Logo / brand guideline files (optional)',{exact:true}).setInputFiles({name:'brand-guidelines.pdf',mimeType:'application/pdf',buffer:Buffer.from('sample attachment')});
 await page.getByRole('button',{name:'Review my brief',exact:true}).click();const review=page.getByRole('region',{name:'Review your customization brief'});await expect(review).toBeVisible();for(const text of ['Example Company','Total units required: 25','Customization level: Trimmed','Logo / brand placement: Left chest','Brand colours: Navy and gold','Preferred collection: Corporate Pro','Fabric features: Windproof','Accessories / features: Removable hood','Sampling preference: I require a physical sample','Approval authority: Procurement lead','Preferred communication: WhatsApp','Files to attach in WhatsApp: brand-guidelines.pdf'])await expect(review.locator('pre')).toContainText(text);
 const url=await page.getByRole('link',{name:'Share brief on WhatsApp'}).getAttribute('href');expect(url).toContain('https://wa.me/26775296591?text=');expect(decodeURIComponent(url!)).toContain('Example Company');
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Download brief'}).click();expect((await downloadPromise).suggestedFilename()).toBe('JD-customization-brief.txt');
 await page.getByRole('button',{name:'Edit brief',exact:true}).click();await expect(page.getByLabel('Organisation / company *',{exact:true})).toHaveValue('Example Company');await expect(page.getByLabel('Trimmed',{exact:true})).toBeChecked();await page.getByLabel('Quantity required (total units) *',{exact:true}).fill('30');await page.getByRole('button',{name:'Review my brief',exact:true}).click();await expect(review.locator('pre')).toContainText('Total units required: 30');expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBe(false);
});
