import { test, expect } from '@playwright/test';
test('gallery deep links, filters and model-specific quotes',async({page})=>{
 await page.goto('/gallery?style=mining-orange');await expect(page.locator('.gallery-description h2')).toHaveText('Mining orange safety jacket');await expect(page.locator('.gallery-card')).toHaveCount(20);
 await page.getByRole('button',{name:'Mining 5',exact:true}).click();await expect(page.locator('.gallery-card')).toHaveCount(5);await page.getByRole('button',{name:'Explore Mining high-vis bodywarmer',exact:true}).click();await expect(page).toHaveURL(/style=mining-bodywarmer/);await expect(page.locator('.gallery-description h2')).toHaveText('Mining high-vis bodywarmer');await page.reload();await expect(page.locator('.gallery-description h2')).toHaveText('Mining high-vis bodywarmer');
 await page.locator('.gallery-description').getByRole('button',{name:'ORDER CUSTOM JACKETS',exact:true}).click();await expect(page.getByLabel('Jacket collection',{exact:true})).toHaveValue('mining');await expect(page.locator('.selected-model')).toContainText('Mining high-vis bodywarmer');
 await page.getByLabel('Contact person *',{exact:true}).fill('Gallery Customer');await page.getByLabel('Business / organization name *',{exact:true}).fill('Example Team');await page.getByLabel('Phone number *',{exact:true}).fill('+26771000000');await page.getByLabel('Preferred colour *',{exact:true}).fill('Yellow');await page.getByLabel('Delivery location *',{exact:true}).fill('Gaborone, Botswana');await page.getByLabel('L quantity',{exact:true}).fill('12');await page.locator('button[type="submit"]').click();await expect(page.locator('.request-preview pre')).toContainText('Jacket Style: Mining high-vis bodywarmer');
});
test('front/back, pointer rotation, keyboard, zoom and gallery navigation',async({page,isMobile})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/gallery');const surface=page.locator('.viewer-surface');await expect(surface).toBeVisible();
 await page.getByRole('button',{name:'Back',exact:true}).click();await expect(page.getByRole('button',{name:'Back',exact:true})).toHaveAttribute('aria-pressed','true');await expect(surface).toHaveAttribute('data-angle',/3\.14/);
 await page.getByRole('button',{name:'Front',exact:true}).click();await expect(page.getByRole('button',{name:'Front',exact:true})).toHaveAttribute('aria-pressed','true');
 await surface.scrollIntoViewIfNeeded();const box=await surface.boundingBox();if(!box)throw new Error('Missing viewer');
 if(isMobile){const cdp=await page.context().newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:box.x+90,y:box.y+170}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:box.x+210,y:box.y+170}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach();}
 else{await page.mouse.move(box.x+100,box.y+180);await page.mouse.down();await page.mouse.move(box.x+230,box.y+180,{steps:10});await page.mouse.up();}
 await expect.poll(async()=>Math.abs(Number(await surface.getAttribute('data-angle')))).toBeGreaterThan(.5);
 await page.getByRole('button',{name:'Reset jacket view'}).click();await expect(surface).toHaveAttribute('data-angle','0.000');await surface.focus();await page.keyboard.press('ArrowRight');await expect(surface).toHaveAttribute('data-angle','0.524');await page.keyboard.press('End');await expect(page.getByRole('button',{name:'Back',exact:true})).toHaveAttribute('aria-pressed','true');
 await page.getByRole('button',{name:'Zoom in',exact:true}).click();await expect(page.locator('.product-viewer')).toHaveClass(/viewer-zoomed/);await page.getByRole('button',{name:'Next jacket'}).click();await expect(page.locator('.gallery-description h2')).toHaveText('Campus crest softshell');await expect(surface).toHaveAttribute('data-angle','0.000');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBe(false);await page.locator('.gallery-showcase').scrollIntoViewIfNeeded();await expect(page.locator('.viewer-poster')).toHaveClass(/is-loaded/);await page.screenshot({path:`test-results/${test.info().project.name}-gallery.png`,fullPage:false});expect(errors).toEqual([]);
});
test('reduced motion and WebGL fallback preserve front/back controls',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'});await page.addInitScript(()=>{const native=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type:string,...args:unknown[]){if(type==='webgl2'||type==='webgl')return null;return native.apply(this,[type,...args] as Parameters<typeof native>)} as typeof native});
 await page.goto('/gallery?style=sport-blue');await expect(page.locator('.viewer-poster')).toBeVisible();await expect(page.getByRole('button',{name:'Start automatic rotation'})).toHaveCount(0);await page.getByRole('button',{name:'Back',exact:true}).click();await expect(page.getByRole('button',{name:'Back',exact:true})).toHaveAttribute('aria-pressed','true');await expect(page.locator('.viewer-poster')).toHaveAttribute('style',/rotateY\(3\.14/);
});
