import { test, expect } from '@playwright/test';
test('industry order generates the complete business request, opens WhatsApp and preserves edits',async({page})=>{
 await page.addInitScript(()=>{window.open=(url)=>{(window as unknown as {opened:string}).opened=String(url);return null}});
 await page.goto('/');await expect(page.locator('.industry-card')).toHaveCount(8);await expect(page.locator('h1')).toContainText('for businesses');
 await page.getByRole('link',{name:'Explore Logistics & Transport',exact:true}).click();await expect(page).toHaveURL('/industries/logistics');await page.getByRole('button',{name:'ORDER CUSTOM JACKETS FOR MY BUSINESS',exact:true}).click();await expect(page.locator('dialog')).toBeVisible();await expect(page.getByLabel('Jacket collection',{exact:true})).toHaveValue('logistics');await expect(page.getByLabel('Industry / sector *',{exact:true})).toHaveValue('logistics');
 await page.getByLabel('Contact person *',{exact:true}).fill('Test Customer');await page.getByLabel('Business / organization name *',{exact:true}).fill('ABC Transport');await page.getByLabel('Phone number *',{exact:true}).fill('+26771000000');await page.getByLabel('Preferred colour *',{exact:true}).fill('Black and red');await page.getByLabel('Jacket style',{exact:true}).fill('Softshell');await page.getByLabel('Delivery location *',{exact:true}).fill('Gaborone, Botswana');await page.getByLabel('Required delivery date',{exact:true}).fill('2026-12-15');
 await page.getByRole('button',{name:'SEND ORDER ON WHATSAPP',exact:true}).click();await expect(page.getByRole('alert')).toContainText('at least one');
 await page.getByLabel('M quantity',{exact:true}).fill('20');await page.getByLabel('XL quantity',{exact:true}).fill('30');await page.getByLabel('Embroidery',{exact:true}).check();await page.getByLabel('Logo',{exact:true}).check();await page.getByLabel('Front branding',{exact:true}).check();await page.getByLabel('Back branding',{exact:true}).check();await page.getByLabel('Additional requirements',{exact:true}).fill('Reflective details for our evening shift');await page.getByLabel('Upload logo / design',{exact:true}).setInputFiles({name:'company-logo.png',mimeType:'image/png',buffer:Buffer.from('test artwork')});
 await page.getByRole('button',{name:'SEND ORDER ON WHATSAPP',exact:true}).click();const preview=page.locator('.request-preview pre');for(const text of ['Business Name: ABC Transport','Industry: Logistics & Transport','Collection: Logistics Pro','Jacket Style: Softshell','Quantity: 50 jackets','Sizes: M: 20, XL: 30','Colours: Black and red','Logo/Branding: Embroidery, Logo, Front branding, Back branding','Delivery Location: Gaborone, Botswana','Required Date: 2026-12-15','Reflective details for our evening shift','company-logo.png','I would like to receive a quotation'])await expect(preview).toContainText(text);
 const link=await page.getByRole('link',{name:'Open WhatsApp'}).getAttribute('href');expect(link).toContain('https://wa.me/26775296591?text=');expect(await page.evaluate(()=>(window as unknown as {opened:string}).opened)).toBe(link);
 await page.getByRole('button',{name:'Edit my request'}).click();await expect(page.getByLabel('Business / organization name *',{exact:true})).toHaveValue('ABC Transport');await expect(page.getByLabel('Back branding',{exact:true})).toBeChecked();await expect(page.getByLabel('M quantity',{exact:true})).toHaveValue('20');await page.getByLabel('XL quantity',{exact:true}).fill('35');await page.getByRole('button',{name:'SEND ORDER ON WHATSAPP',exact:true}).click();await expect(preview).toContainText('Quantity: 55 jackets');await page.getByRole('button',{name:'Close order form'}).click();await expect(page.locator('dialog')).toHaveCount(0);
});
test('B2B homepage, inquiry, five-step process, 3D controls and responsive layout',async({page,isMobile})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await expect(page.locator('.steps .step')).toHaveCount(5);await expect(page.locator('.custom-options>span')).toHaveCount(10);await expect(page.locator('.served-teams>span')).toHaveCount(12);const chat=page.locator('.hero-actions').getByRole('link',{name:'CHAT ON WHATSAPP'});expect(decodeURIComponent((await chat.getAttribute('href'))!)).toContain('Hello JD Jackets, I am interested in custom jackets for my business and would like to get more information.');
 if(isMobile){await expect(page.locator('.mobile-contact-bar')).toBeInViewport();await page.locator('#faq').scrollIntoViewIfNeeded();await expect(page.locator('.mobile-contact-bar')).toBeInViewport();await page.locator('.mobile-contact-bar').getByRole('button',{name:'ORDER NOW'}).click();await expect(page.locator('dialog')).toBeVisible();await page.getByRole('button',{name:'Close order form'}).click()}
 await page.getByRole('button',{name:'Preview Campus Pro'}).click();await expect(page.getByRole('button',{name:'Preview Campus Pro'})).toHaveAttribute('aria-pressed','true');await page.getByRole('button',{name:'Back',exact:true}).click();await page.locator('#faq').scrollIntoViewIfNeeded();await page.getByRole('button',{name:'Can I order different sizes in one order?'}).click();await expect(page.locator('#faq-1')).toBeVisible();await page.getByRole('button',{name:'How do I place an order?'}).click();await expect(page.locator('#faq-9')).toContainText('Tap Send in WhatsApp');
 for(const image of await page.locator('.product-visual img').all()){await image.scrollIntoViewIfNeeded();await expect.poll(()=>image.evaluate(i=>(i as HTMLImageElement).complete&&(i as HTMLImageElement).naturalWidth>0)).toBe(true)}
 for(const id of ['industries','customisation','how-it-works','who-we-serve','inquiry','faq','final-cta']){await page.locator('#'+id).scrollIntoViewIfNeeded();await page.waitForTimeout(250)}expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBe(false);await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));await page.waitForTimeout(400);await page.screenshot({path:`test-results/${test.info().project.name}-b2b-home.png`,fullPage:true});expect(errors).toEqual([]);
});
test('all eight industry deep links explain the audience and preselect the right order',async({page})=>{
 test.setTimeout(60000);
 for(const id of ['corporate','logistics','tactical','campus','safari','sport','mining','healthcare']){await page.goto(`/industries/${id}/`);await expect(page.locator('.industry-audience')).toBeVisible();await expect(page.locator('.industry-details li')).toHaveCount(6);expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBe(false);await page.locator('header').getByRole('button',{name:'ORDER CUSTOM JACKETS',exact:true}).click();await expect(page.getByLabel('Industry / sector *',{exact:true})).toHaveValue(id);await expect(page.getByLabel('Jacket collection',{exact:true})).toHaveValue(id);await page.getByRole('button',{name:'Close order form'}).click();if(id==='mining')await page.screenshot({path:`test-results/${test.info().project.name}-industry.png`,fullPage:true})}
});
