import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, ArrowUpRight, Check, ChevronLeft, ChevronRight, Menu, X } from 'lucide-react';
import { collections, type Collection } from '../data';
import OrderForm from '../components/OrderForm';
import ProductViewer from './ProductViewer';
import JacketPhoto from './JacketPhoto';
import { galleryProducts, type GalleryProduct } from './products';
export default function Gallery(){
 const initial=galleryProducts.find(p=>p.id===new URLSearchParams(window.location.search).get('style'))||galleryProducts[0];
 const [product,setProduct]=useState(initial),[filter,setFilter]=useState('all'),[menu,setMenu]=useState(false),[order,setOrder]=useState<Collection|null>(null);const stage=useRef<HTMLElement>(null);
 const collection=collections.find(c=>c.id===product.collection)!;
 const filtered=galleryProducts.filter(p=>filter==='all'||p.collection===filter),index=galleryProducts.indexOf(product);
 function choose(p:GalleryProduct,scroll=true){setProduct(p);window.history.replaceState(null,'',`/gallery?style=${p.id}`);if(scroll)stage.current?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'})}
 useEffect(()=>{document.title='Jacket Gallery — Every angle. Every possibility. | JD Jackets';},[]);
 return <><div className="announcement"><span>YOUR BRAND. FROM EVERY ANGLE.</span><a href="/">Back to JD Jackets <ArrowUpRight size={12}/></a></div><header><a className="logo" href="/" aria-label="JD Jackets home"><span className="logo-mark">JD<span className="logo-dot"/></span><span className="logo-text">JACKETS<small>BY JD & CO</small></span></a><nav className={menu?'open':''} aria-label="Main navigation"><a href="/#collections">Our jackets</a><a href="/gallery" aria-current="page">Gallery</a><a href="/#customisation">Make it yours</a><a href="/#how-it-works">How it works</a></nav><button className="button header-cta" onClick={()=>setOrder(collection)}>Get a custom quote <ArrowUpRight size={16}/></button><button className="menu-button icon-button" aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
 <main className="gallery-page"><section className="gallery-intro"><a className="gallery-back" href="/"><ArrowLeft size={14}/> Back to home</a><div className="section-heading"><div><span className="eyebrow"><span className="tiny-square"/> THE JACKET GALLERY</span><h1>Every angle.<br/><span className="muted">Every possibility.</span></h1></div><p>Explore the details. Find your team’s signature.<br/>20 styles, shown front and back. Made to be yours.</p></div></section>
 <section ref={stage} className="gallery-showcase" aria-label="Selected jacket"><div className="gallery-stage"><span className="gallery-stage-top"><span>{collection.name.toUpperCase()}™</span><span>{String(index+1).padStart(2,'0')} / 20</span></span><span className="gallery-watermark" aria-hidden="true">{collection.id.toUpperCase()}</span><ProductViewer key={product.id} product={product}/></div><div className="gallery-description"><span className="eyebrow"><span className="tiny-square"/> {collection.tag}</span><h2>{product.name}</h2><p>{collection.description}</p><div className="gallery-specs"><div><span>COLLECTION</span><strong>{collection.name}</strong></div><div><span>STYLE</span><strong>{product.kind}</strong></div><div><span>COLOUR SHOWN</span><strong>{product.colour}</strong></div><div><span>MAKE IT YOURS</span><strong>Logo, colours & fit</strong></div></div><div className="gallery-promises"><span><Check size={14}/> Matching front & back views</span><span><Check size={14}/> Your branding. Your identity.</span></div><button className="button primary" onClick={()=>setOrder(collection)}>Customize this jacket <ArrowUpRight size={18}/></button><p className="gallery-help">Like this style? Tell us your colours, sizes and branding. We’ll take care of the details.</p><div className="gallery-pagination"><button aria-label="Previous jacket" onClick={()=>choose(galleryProducts[(index-1+galleryProducts.length)%galleryProducts.length],false)}><ChevronLeft size={17}/> Previous</button><a href="#gallery-styles">See all styles</a><button aria-label="Next jacket" onClick={()=>choose(galleryProducts[(index+1)%galleryProducts.length],false)}>Next <ChevronRight size={17}/></button></div></div></section>
 <section className="gallery-catalogue" id="gallery-styles"><div className="section-heading"><div><span className="eyebrow"><span className="tiny-square"/> FIND YOUR SIGNATURE</span><h2>Built for your world.</h2></div><span className="gallery-style-count" role="status">{filtered.length} styles to explore</span></div><div className="gallery-filters" aria-label="Filter gallery styles"><button aria-pressed={filter==='all'} className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>All styles <span>20</span></button>{collections.filter(c=>galleryProducts.some(p=>p.collection===c.id)).map(c=><button key={c.id} className={filter===c.id?'active':''} aria-pressed={filter===c.id} onClick={()=>setFilter(c.id)}>{c.name.replace(' Pro','')} <span>{galleryProducts.filter(p=>p.collection===c.id).length}</span></button>)}</div><div className="gallery-grid">{filtered.map(p=><button className={`gallery-card ${p.id===product.id?'selected':''}`} key={p.id} onClick={()=>choose(p)} aria-label={`Explore ${p.name}`} aria-pressed={p.id===product.id}><div className="gallery-card-photo"><span className="gallery-card-type">{p.kind.toUpperCase()}</span><JacketPhoto product={p}/><span className="gallery-card-action">EXPLORE FRONT & BACK <ArrowUpRight size={16}/></span></div><div className="gallery-card-caption"><span>{collections.find(c=>c.id===p.collection)?.name}</span><h3>{p.name}</h3><span>{p.colour} <ArrowRight size={14}/></span></div></button>)}</div><div className="gallery-end"><p>Found your team’s next look?</p><button className="button primary" onClick={()=>setOrder(collection)}>Let’s make it yours <ArrowUpRight size={18}/></button></div></section></main>
 <footer><div className="footer-top"><a className="logo" href="/"><span className="logo-mark">JD<span className="logo-dot"/></span><span className="logo-text">JACKETS<small>BY JD & CO</small></span></a><p>Purpose-built outerwear.<br/>Made unmistakably yours.</p><div><a href="/#collections">Our jackets</a><a href="/gallery">Gallery</a><a href="/#faq">FAQs</a><a href="/">Back to home</a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} JD Jackets by JD & Co. All rights reserved.</span><span>YOUR BRAND. WORN WITH PRIDE.</span><a href="#">Back to top ↑</a></div></footer>{order&&<OrderForm collection={order} productName={product.name} onClose={()=>setOrder(null)}/>}</>
}
