import { Component, lazy, Suspense, useCallback, useEffect, useRef, useState, type ReactNode, type PointerEvent, type KeyboardEvent, type CSSProperties } from 'react';
import { Maximize2, Minimize2, MoveHorizontal, Pause, Play, RotateCcw } from 'lucide-react';
import JacketPhoto from './JacketPhoto';
import type { GalleryProduct } from './products';
const JacketModel=lazy(()=>import('./JacketModel'));
class ViewerBoundary extends Component<{children:ReactNode;onError:()=>void},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true}};componentDidCatch(){this.props.onError()};render(){return this.state.failed?null:this.props.children}}
export default function ProductViewer({product,compact=false}:{product:GalleryProduct;compact?:boolean}){
 const host=useRef<HTMLDivElement>(null),target=useRef(0),current=useRef(0),drag=useRef<{x:number;start:number;id:number}|null>(null);
 const [angle,setAngle]=useState(0),[auto,setAuto]=useState(false),[zoom,setZoom]=useState(false),[ready,setReady]=useState(false),[visible,setVisible]=useState(true),[failed,setFailed]=useState(false);
 const [reduced,setReduced]=useState(()=>window.matchMedia('(prefers-reduced-motion: reduce)').matches);
 const [webgl]=useState(()=>{try{return !!document.createElement('canvas').getContext('webgl2')}catch{return false}});
 const onReady=useCallback(()=>setReady(true),[]),onError=useCallback(()=>setFailed(true),[]);
 useEffect(()=>{setAngle(0);setAuto(false);setZoom(false);target.current=0;current.current=0;drag.current=null},[product.id]);
 useEffect(()=>{const media=window.matchMedia('(prefers-reduced-motion: reduce)');const changed=()=>{setReduced(media.matches);if(media.matches)setAuto(false)};media.addEventListener('change',changed);const observer=new IntersectionObserver(entries=>setVisible(entries[0].isIntersecting),{threshold:.01});if(host.current)observer.observe(host.current);return()=>{media.removeEventListener('change',changed);observer.disconnect()}},[]);
 useEffect(()=>{if(!auto)return;const timer=window.setInterval(()=>setAngle(current.current),200);return()=>window.clearInterval(timer)},[auto]);
 function rotate(value:number){setAuto(false);target.current=value;if(!webgl||failed)current.current=value;setAngle(value)}
 function face(back:boolean){const wanted=back?Math.PI:0;rotate(current.current+Math.atan2(Math.sin(wanted-current.current),Math.cos(wanted-current.current)))}
 function down(e:PointerEvent<HTMLDivElement>){if(e.button!==0)return;setAuto(false);drag.current={x:e.clientX,start:current.current,id:e.pointerId};e.currentTarget.setPointerCapture(e.pointerId);e.currentTarget.focus({preventScroll:true})}
 function move(e:PointerEvent<HTMLDivElement>){if(drag.current?.id===e.pointerId)rotate(drag.current.start+(e.clientX-drag.current.x)*.012)}
 function release(){drag.current=null}
 function keyboard(e:KeyboardEvent<HTMLDivElement>){if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();rotate(target.current+(e.key==='ArrowRight'?1:-1)*Math.PI/6)}if(e.key==='Home'){e.preventDefault();face(false)}if(e.key==='End'){e.preventDefault();face(true)}}
 const back=Math.cos(angle)<0;
 return <div className={`product-viewer ${compact?'viewer-compact':''} ${zoom?'viewer-zoomed':''}`} data-product={product.id}><div ref={host} className="viewer-surface" role="region" aria-roledescription="interactive product viewer" aria-label={`${product.name}. Drag or swipe to rotate. Arrow keys rotate, Home shows front, End shows back.`} tabIndex={0} data-angle={angle.toFixed(3)} onPointerDown={down} onPointerMove={move} onPointerUp={release} onPointerCancel={release} onLostPointerCapture={release} onKeyDown={keyboard}><div className="viewer-halo"/><div className="viewer-platform"/><div className="viewer-object" style={{'--viewer-zoom':zoom?1.22:1} as CSSProperties}><div className={`viewer-poster ${ready&&!failed&&webgl?'is-loaded':''}`} style={{transform:`rotateY(${angle}rad)`}}><div className="poster-front"><JacketPhoto product={product} eager/></div><div className="poster-back"><JacketPhoto product={product} back eager/></div></div>{webgl&&!failed&&<div className="viewer-canvas" aria-hidden="true"><ViewerBoundary onError={onError}><Suspense fallback={null}><JacketModel product={product} target={target} current={current} auto={auto&&visible} reduced={reduced} visible={visible} onReady={onReady}/></Suspense></ViewerBoundary></div>}</div><span className="viewer-drag"><MoveHorizontal size={15}/> Drag or swipe to rotate</span></div><div className="viewer-controls"><div className="viewer-faces" aria-label="Jacket view"><button aria-pressed={!back} onClick={()=>face(false)}>Front</button><button aria-pressed={back} onClick={()=>face(true)}>Back</button></div><div className="viewer-tools"><button onClick={()=>{target.current=0;current.current=0;setAngle(0);setAuto(false);setZoom(false)}} aria-label="Reset jacket view"><RotateCcw size={16}/></button><button onClick={()=>setZoom(!zoom)} aria-label={zoom?'Zoom out':'Zoom in'}>{zoom?<Minimize2 size={16}/>:<Maximize2 size={16}/>}</button>{webgl&&!failed&&!reduced&&<button aria-label={auto?'Pause automatic rotation':'Start automatic rotation'} aria-pressed={auto} onClick={()=>setAuto(!auto)}>{auto?<Pause size={16}/>:<Play size={16}/>}</button>}</div></div></div>
}
