import { useEffect, useState, type ReactNode } from 'react';
import { ArrowUpRight, Menu, X, MessageCircle } from 'lucide-react';
import { collections, inquiryMessage, whatsappUrl, type Collection } from '../data';
import OrderForm from './OrderForm';
export function openOrder(collectionId?:string){window.dispatchEvent(new CustomEvent('jd-order',{detail:collectionId}))}
export function Brand(){return <a className="logo" href="/" aria-label="JD Jackets home"><img className="logo-image" src="/brand/jd-co-bw-logo.png" alt="JD & Co.BW — Jacket Manufacturers of Distinction" width={1774} height={887} fetchPriority="high"/></a>}
export function SiteHeader({onQuote}:{onQuote?:()=>void}){
 const [open,setOpen]=useState(false),[order,setOrder]=useState<Collection|null>(null);
 useEffect(()=>{const listener=(e:Event)=>setOrder(collections.find(c=>c.id===(e as CustomEvent).detail)||collections[0]);window.addEventListener('jd-order',listener);return()=>window.removeEventListener('jd-order',listener)},[]);
 const start=()=>{setOpen(false);if(onQuote)onQuote();else setOrder(collections.find(c=>c.id===window.location.pathname.split('/')[2])||collections[0])};
 return <><div className="announcement"><span>CUSTOM BRANDED JACKETS FOR BUSINESSES & ORGANIZATIONS.</span><a href="/client-journey">One partner. Every step. <ArrowUpRight size={12}/></a></div><header><Brand/><nav className={open?'open':''} aria-label="Main navigation">{[['/','Home'],['/#industries','Industries'],['/gallery','Custom Jackets'],['/#how-it-works','How It Works'],['/about','About Us'],['/#faq','FAQ'],['/#contact','Contact']].map(([url,label])=><a key={url} href={url} aria-current={window.location.pathname===url?'page':undefined} onClick={()=>setOpen(false)}>{label}</a>)}</nav><button className="button primary header-cta" onClick={start}>ORDER CUSTOM JACKETS <ArrowUpRight size={16}/></button><button className="menu-button icon-button" aria-label={open?'Close navigation':'Open navigation'} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></header><div className="mobile-contact-bar"><a href={whatsappUrl(inquiryMessage)} target="_blank" rel="noreferrer"><MessageCircle size={18}/> WHATSAPP</a><button onClick={start}>ORDER NOW <ArrowUpRight size={18}/></button></div>{order&&<OrderForm collection={order} onClose={()=>setOrder(null)}/>}</>
}
export function SiteFooter(){return <footer id="contact"><div className="footer-top"><Brand/><p>Custom branded jackets for businesses,<br/>organisations and professional teams.</p><div><a href="/about">About us</a><a href="/client-journey">Client journey</a><a href="/customization-brief">Detailed project brief</a><a href="/gallery">Gallery</a></div></div><div className="company-contact"><span>Gaborone, Botswana</span><a href="mailto:info@jdandcobw.com">info@jdandcobw.com</a><a href="tel:+26775296591">+267 75 296 591</a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} JD Jackets by JD & Co BW. All rights reserved.</span><span>FEEL IT. WEAR IT. REPRESENT IT. PROUDLY.</span><a href="#">Back to top ↑</a></div></footer>}
export default function SiteLayout({title,description,children}:{title:string;description:string;children:ReactNode}){
 useEffect(()=>{document.title=`${title} | JD Jackets by JD & Co BW`;document.querySelector('meta[name="description"]')?.setAttribute('content',description)},[title,description]);
 return <><SiteHeader/><main className="company-page">{children}</main><SiteFooter/></>
}
export function ProjectCTA(){return <section className="company-cta"><span className="eyebrow">YOUR VISION. OUR CRAFT. YOUR IDENTITY.</span><h2>Let’s build something<br/>that represents you.</h2><button className="button primary" onClick={()=>openOrder()}>ORDER CUSTOM JACKETS <ArrowUpRight size={18}/></button><a className="company-cta-link" href={whatsappUrl(inquiryMessage)} target="_blank" rel="noreferrer">CHAT ON WHATSAPP →</a><a className="company-cta-link" href="/gallery">Explore the jackets first →</a></section>}
