import { useEffect, useState, type ReactNode } from 'react';
import { ArrowUpRight, Menu, X } from 'lucide-react';
export function Brand(){return <a className="logo" href="/" aria-label="JD Jackets home"><span className="logo-mark">JD<span className="logo-dot"/></span><span className="logo-text">JACKETS<small>BY JD & CO BW</small></span></a>}
export function SiteHeader({onQuote}:{onQuote?:()=>void}){
 const [open,setOpen]=useState(false);
 return <><div className="announcement"><span>PROFESSIONAL OUTERWEAR. PERSONAL IDENTITY.</span><a href="/client-journey">One partner. Every step. <ArrowUpRight size={12}/></a></div><header><Brand/><nav className={open?'open':''} aria-label="Main navigation">{[['/#collections','Our jackets'],['/gallery','Gallery'],['/about','About us'],['/client-journey','Client journey'],['/customization-brief','Customization brief']].map(([url,label])=><a key={url} href={url} aria-current={window.location.pathname===url?'page':undefined} onClick={()=>setOpen(false)}>{label}</a>)}</nav>{onQuote?<button className="button header-cta" onClick={()=>{setOpen(false);onQuote()}}>Get a custom quote <ArrowUpRight size={16}/></button>:<a className="button header-cta" href="/customization-brief">Start your project <ArrowUpRight size={16}/></a>}<button className="menu-button icon-button" aria-label={open?'Close navigation':'Open navigation'} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></header></>
}
export function SiteFooter(){return <footer><div className="footer-top"><Brand/><p>Rooted in Botswana. Made for Africa.<br/>Ready for the world.</p><div><a href="/about">About us</a><a href="/client-journey">Client journey</a><a href="/customization-brief">Start a brief</a><a href="/gallery">Gallery</a></div></div><div className="company-contact"><span>Gaborone, Botswana</span><a href="mailto:info@jdandcobw.com">info@jdandcobw.com</a><a href="tel:+26775296591">+267 75 296 591</a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} JD Jackets by JD & Co BW. All rights reserved.</span><span>FEEL IT. WEAR IT. REPRESENT IT. PROUDLY.</span><a href="#">Back to top ↑</a></div></footer>}
export default function SiteLayout({title,description,children}:{title:string;description:string;children:ReactNode}){
 useEffect(()=>{document.title=`${title} | JD Jackets by JD & Co BW`;document.querySelector('meta[name="description"]')?.setAttribute('content',description)},[title,description]);
 return <><SiteHeader/><main className="company-page">{children}</main><SiteFooter/></>
}
export function ProjectCTA(){return <section className="company-cta"><span className="eyebrow">YOUR VISION. OUR CRAFT. YOUR IDENTITY.</span><h2>Let’s build something<br/>that represents you.</h2><a className="button primary" href="/customization-brief">Start your customization brief <ArrowUpRight size={18}/></a><a className="company-cta-link" href="/gallery">Explore the jackets first →</a></section>}
