import { lazy, Suspense, useEffect, useState } from 'react';
import { ArrowUpRight, ArrowRight, Check, ChevronDown, ShieldCheck, Palette, Layers, Ruler, MessageCircle, Plus, Minus, Users, Building2, Eye, BadgeCheck, Shirt } from 'lucide-react';
import { collections, industries, inquiryMessage, whatsappUrl, type Collection } from './data';
import OrderForm from './components/OrderForm';
import { SiteHeader, SiteFooter } from './components/SiteLayout';
import ProductViewer from './gallery/ProductViewer';
import JacketPhoto from './gallery/JacketPhoto';
import { collectionPreviews, galleryProducts } from './gallery/products';
const ClothStudy=lazy(()=>import('@designcodeio/threeui/components/ClothStudy').then(m=>({default:m.ClothStudy})));
const RippleStudy=lazy(()=>import('@designcodeio/threeui/components/RippleStudy').then(m=>({default:m.RippleStudy})));
const faqs=[
 ['Can I customize the jacket with my company logo?','Yes. Share your company logo, brand colours and preferred placement. We work with you to confirm the branding and artwork before production.'],
 ['Can I order different sizes in one order?','Yes. Enter a quantity for each size in the order form, from XS to XXXL, or include custom fitting requirements. Your total is calculated automatically and included in your WhatsApp request.'],
 ['What is the minimum order quantity?','Minimum quantities depend on the jacket style and customization. Send your business requirements on WhatsApp and our team will confirm the applicable minimum and quotation.'],
 ['What jacket styles are available?','Our eight JD Pro collections include puffer jackets, softshells, parkas, windbreakers, fleece, bodywarmers and other collection-specific styles. Explore the gallery or ask us to recommend a style for your team.'],
 ['Can I choose my own colours?','Yes. Tell us your preferred colours or brand colour codes. Our team will discuss suitable fabrics, trims and design options and confirm availability with you.'],
 ['Can you embroider or print our logo?','Embroidery and printing are branding options. Select what you need in the order form, including front, back or sleeve placement. We will confirm the right method for your artwork and jacket.'],
 ['Can I upload my own design?','Yes. Select your logo, artwork or reference image in the form. The filenames are added to your WhatsApp message. Files stay on your device, so attach the actual artwork in the WhatsApp conversation.'],
 ['How long does production take?','Timing depends on your jacket style, quantity, customization and approvals. Include your required delivery date and we will confirm a production schedule with your quotation.'],
 ['Do you deliver to my location?','Include your town or city and country in the order form. Our team will confirm delivery availability, arrangements, costs and timing for your location on WhatsApp.'],
 ['How do I place an order?','Click Order Custom Jackets, enter your business details, jacket requirements, sizes and branding, then click Send Order on WhatsApp. Tap Send in WhatsApp to share your request. Our team discusses your quotation, design, approval and production details with you.']
];
const customization=[['Jacket style',Shirt],['Colours',Palette],['Company logo',BadgeCheck],['Embroidery',Layers],['Printing',Palette],['Front branding',BadgeCheck],['Back branding',Layers],['Sleeve branding',Shirt],['Sizes',Ruler],['Quantity',Users]] as const;
export default function App(){
 const [selected,setSelected]=useState<Collection|null>(null),[heroStyle,setHeroStyle]=useState('corporate'),[faq,setFaq]=useState<number|null>(0),[materialVisible,setMaterialVisible]=useState(false),[ctaVisible,setCtaVisible]=useState(false);
 useEffect(()=>{document.title='Custom Jackets for Businesses & Organizations | JD Jackets';document.querySelector('meta[name="description"]')?.setAttribute('content','Custom branded jackets for businesses, organisations and professional teams. Explore eight industries, choose your styles, colours, sizes and branding, and request your quotation on WhatsApp.');const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');if(e.target.id==='material-panel')setMaterialVisible(true);if(e.target.id==='final-cta')setCtaVisible(true);observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(e=>observer.observe(e));return()=>observer.disconnect()},[]);
 const heroProduct=collectionPreviews[heroStyle];const order=(c:Collection=collections[0])=>setSelected(c);
 return <><SiteHeader onQuote={()=>order()}/><main className="b2b-home"><section className="hero"><div className="hero-copy"><span className="eyebrow"><span className="status-dot"/> CUSTOM BRANDED OUTERWEAR FOR YOUR TEAM</span><h1>Custom jackets<br/>for businesses<br/><span className="orange">& organizations.</span></h1><p>Create professional branded jackets for your staff, team, company or organization. Choose your style, colours, sizes and branding, then tell us what you need.</p><div className="hero-actions"><button className="button primary" onClick={()=>order()}>ORDER CUSTOM JACKETS <ArrowUpRight size={19}/></button><a className="hero-link" href={whatsappUrl(inquiryMessage)} target="_blank" rel="noreferrer"><MessageCircle size={17}/> CHAT ON WHATSAPP</a></div><div className="hero-assurance"><span><Check size={14}/> Your company logo & colours</span><span><Check size={14}/> Mixed sizes for your team</span></div><a href="#industries" className="hero-industry-link">Find your industry <ArrowRight size={16}/></a></div><div className="hero-stage"><span className="stage-word">YOUR TEAM</span><div className="orbit orbit-one"/><div className="orbit orbit-two"/><span className="stage-index">01 / 08</span><span className="stage-label">CUSTOMIZED FOR YOUR BUSINESS</span><div className="jacket-scene hero-viewer"><ProductViewer key={heroProduct.id} product={heroProduct} compact/></div><div className="callout callout-one"><span/>Your company.<br/><strong>Your identity.</strong></div><div className="callout callout-two"><span/>Staff. Teams. Organisations.<br/><strong>One professional look.</strong></div><div className="stage-bottom"><div><span className="eyebrow">JD {heroStyle.toUpperCase()} PRO™</span><p>{heroStyle==='corporate'?'Executive Puffer Jacket':'Campus Crest Softshell'}</p><div className="hero-style-options"><button className={heroStyle==='corporate'?'active':''} onClick={()=>setHeroStyle('corporate')} aria-label="Preview Corporate Pro" aria-pressed={heroStyle==='corporate'}>Corporate</button><button className={heroStyle==='campus'?'active':''} onClick={()=>setHeroStyle('campus')} aria-label="Preview Campus Pro" aria-pressed={heroStyle==='campus'}>Campus</button></div></div><a className="stage-gallery-link" href="/gallery">Explore jacket examples <ArrowUpRight size={14}/></a></div></div><a className="scroll-cue" href="#industries"><span>EXPLORE ALL 8 INDUSTRIES</span><ChevronDown size={16}/></a></section><div className="value-strip"><span><Building2/> FOR BUSINESSES</span><span><Users/> FOR ORGANIZATIONS</span><span><Palette/> CUSTOM BRANDING</span><span><MessageCircle/> ORDER THROUGH WHATSAPP</span></div>
 <section className="collections section-pad" id="industries"><span id="collections" className="section-anchor"/><div className="section-heading"><div><span className="eyebrow"><span className="tiny-square"/> EIGHT INDUSTRIES. YOUR BUSINESS.</span><h2>Custom jackets<br/><span className="muted">for your industry.</span></h2></div><p>Find the teams and workplaces we serve.<br/>Select your industry to explore jackets for your organisation.</p></div><div className="industry-grid">{industries.map((industry,i)=>{const collection=collections.find(c=>c.id===industry.id)!;return <article className="industry-card" key={industry.id}><a className="product-visual" href={`/industries/${industry.id}`} aria-label={`Explore ${industry.name}`}><span className="product-tag">{collection.name.toUpperCase()}™</span><span className="product-number">0{i+1}</span><JacketPhoto product={collectionPreviews[industry.id]}/>{industry.id==='tactical'&&<span className="preview-note">ILLUSTRATIVE TECHNICAL STYLE</span>}<span className="product-hover">EXPLORE YOUR INDUSTRY <ArrowUpRight size={18}/></span></a><div className="industry-card-copy"><h3><a href={`/industries/${industry.id}`}>{industry.name}</a></h3><p>{industry.audience}</p><a className="text-button" href={`/industries/${industry.id}`}>Explore Jackets <ArrowUpRight size={16}/></a></div></article>})}</div></section>
 <section className="business-benefits section-pad"><div className="section-heading"><div><span className="eyebrow"><span className="tiny-square"/> YOUR PEOPLE. YOUR BUSINESS IDENTITY.</span><h2>Why businesses choose<br/><span className="muted">custom jackets.</span></h2></div></div><div className="business-benefit-grid">{[[Building2,'Professional appearance','A coordinated look for staff, client visits and company activities.'],[Users,'Team identity','A shared sense of belonging across roles, locations and departments.'],[Eye,'Brand visibility','Your colours and logo, representing your business wherever your people go.'],[BadgeCheck,'Staff & company branding','Recognisable names, roles and company details, placed where they matter.']].map(([Icon,title,text])=>{const BenefitIcon=Icon as typeof Users;return <article key={String(title)}><BenefitIcon size={27}/><h3>{String(title)}</h3><p>{String(text)}</p></article>})}</div></section>
 <section className="customisation section-pad" id="customisation"><div className="custom-visual reveal" id="material-panel"><div className="fabric-art" aria-label="Animated fabric study from ThreeUI">{materialVisible&&!window.matchMedia('(prefers-reduced-motion: reduce)').matches&&<Suspense fallback={<div className="cloth-fallback"/>}><ClothStudy mode="dark" hue={20} saturation={.65} style={{width:'100%',height:'100%'}}/></Suspense>}<div className="custom-jacket-display"><JacketPhoto product={galleryProducts[3]}/><span className="custom-branding-note">YOUR LOGO.<br/>YOUR COLOURS.</span></div><div className="material-caption"><span className="eyebrow">YOUR BRAND. WOVEN INTO EVERY DETAIL.</span><span>Plain · Trimmed · Signature Sublimation</span></div></div><div className="custom-swatch"><span>YOUR COMPANY COLOURS.</span><div>{['#20221f','#243849','#bdc2be','#e85626','#c69f51','#5d6552'].map(col=><i key={col} style={{background:col}}/>)}</div></div></div><div className="custom-copy reveal"><span className="eyebrow"><span className="tiny-square"/> CUSTOMIZATION OPTIONS</span><h2>Customize<br/><span className="orange">your jacket.</span></h2><p>Start with a jacket style, then build a professional identity around your business. Tell us the details you need; we’ll confirm the right options for your order.</p><div className="custom-options">{customization.map(([text,Icon])=><span key={text}><Icon size={18}/>{text}</span>)}</div><button className="button primary" onClick={()=>order()}>ORDER CUSTOM JACKETS <ArrowUpRight size={18}/></button><a className="detailed-brief-link" href="/customization-brief">Planning a detailed project? Complete a full brief →</a></div></section>
 <section className="process section-pad" id="how-it-works"><div className="section-heading"><div><span className="eyebrow"><span className="tiny-square"/> SIMPLE FROM THE START</span><h2>How it works.<br/><span className="muted">From your brief to your team.</span></h2></div><a className="text-button" href="/client-journey">See the full client journey <ArrowUpRight size={18}/></a></div><div className="steps">{[['Choose Your Industry','Tell us what type of business or organization you represent.'],['Tell Us What You Need','Choose your jacket style, quantity, colours, sizes and branding requirements.'],['Send Your Order on WhatsApp','Your requirements are automatically organised into a WhatsApp message.'],['Get Your Quote','Our team reviews your requirements and discusses pricing and production details with you.'],['Approve & Produce','Once the design, sample and order details are approved, production begins and your jackets are prepared for delivery.']].map(([title,desc],i)=><div className="step" key={title}><div className="step-top"><span>0{i+1}</span>{i<4?<ArrowRight size={22}/>:<Check size={24}/>}</div><h3>{title}</h3><p>{desc}</p></div>)}</div></section>
 <section className="who-we-serve section-pad" id="who-we-serve"><div><span className="eyebrow"><span className="tiny-square"/> WHO WE SERVE</span><h2>Your company.<br/>Your people.<br/><span className="muted">Your identity.</span></h2><p>JD Jackets creates custom branded jackets for business and organisational orders. We help teams look professional, feel connected and represent their brand with pride.</p><a className="text-button" href="/about">About JD & Co BW <ArrowUpRight size={18}/></a></div><div className="served-teams">{['Companies','Businesses','Corporate teams','Staff teams','Organizations','Schools','Construction companies','Security companies','Logistics companies','Hospitality businesses','Sports teams','Events & associations'].map(t=><span key={t}><Check size={16}/>{t}</span>)}</div></section>
 <section className="gallery-teaser section-pad"><div><span className="eyebrow"><span className="tiny-square"/> JACKET GALLERY</span><h2>Custom jacket examples.<br/><span className="muted">Every angle. Every detail.</span></h2><p>Explore 20 front-and-back jacket styles for your business or team. Rotate with your mouse or touch, review the details and use a style as the starting point for your order.</p><a className="button primary" href="/gallery">EXPLORE CUSTOM JACKETS <ArrowUpRight size={18}/></a></div><a className="teaser-jackets" href="/gallery" aria-label="Explore the custom jacket gallery"><JacketPhoto product={galleryProducts[15]}/><JacketPhoto product={galleryProducts[7]} back/><span className="teaser-badge">YOUR COMPANY LOGO.<br/><strong>YOUR TEAM COLOURS.</strong></span></a></section>
 <section className="quick-inquiry section-pad" id="inquiry"><MessageCircle size={38}/><div><span className="eyebrow">HAVE A QUESTION?</span><h2>Let’s talk about your team.</h2><p>Chat with us directly on WhatsApp and tell us what you need.</p></div><a className="button primary" href={whatsappUrl(inquiryMessage)} target="_blank" rel="noreferrer">CHAT ON WHATSAPP <ArrowUpRight size={18}/></a></section>
 <section className="faq section-pad" id="faq"><div className="faq-heading"><span className="eyebrow"><span className="tiny-square"/> BUSINESS ORDERS. CLEAR ANSWERS.</span><h2>Your questions,<br/>answered.</h2><p>Need advice for your business?<br/>Our team is ready to help.</p><a className="text-button" href={whatsappUrl(inquiryMessage)} target="_blank" rel="noreferrer">CHAT ON WHATSAPP <MessageCircle size={18}/></a></div><div className="faq-list">{faqs.map(([q,a],i)=><div className="faq-item" key={q}><button onClick={()=>setFaq(faq===i?null:i)} aria-expanded={faq===i} aria-controls={`faq-${i}`}>{q}{faq===i?<Minus size={18}/>:<Plus size={18}/>}</button><div id={`faq-${i}`} hidden={faq!==i}><p>{a}</p></div></div>)}</div></section>
 <section className="final-cta reveal" id="final-cta"><div className="cta-ripple" aria-hidden="true">{ctaVisible&&!window.matchMedia('(prefers-reduced-motion: reduce)').matches&&<Suspense fallback={null}><RippleStudy mode="dark" style={{width:'100%',height:'100%'}}/></Suspense>}</div><div className="cta-decoration">JD</div><span className="eyebrow">CUSTOM JACKETS FOR BUSINESSES & ORGANIZATIONS</span><h2>Ready to create custom jackets<br/>for your business?</h2><div className="final-actions"><button className="button cream" onClick={()=>order()}>ORDER CUSTOM JACKETS <ArrowUpRight size={20}/></button><a className="button cta-whatsapp" href={whatsappUrl(inquiryMessage)} target="_blank" rel="noreferrer">CHAT ON WHATSAPP <MessageCircle size={18}/></a></div><p>Your staff. Your team. Your company identity.</p></section></main><SiteFooter/>{selected&&<OrderForm collection={selected} onClose={()=>setSelected(null)}/>}</>
}
