export const collections = [
 {id:'corporate',name:'Corporate Pro',type:'Business',tag:'THE EVERYDAY STANDARD',description:'A professional finish. An unmistakable identity. Made for the people behind your business.',features:['Puffer · Softshell · Parka','Plain, trimmed or sublimated'],color:'#424b57'},
 {id:'logistics',name:'Logistics Pro',type:'Industry',tag:'BUILT FOR EVERY DELIVERY',description:'Flexible, practical jackets for the teams that keep your business moving.',features:['Softshell · Fleece · Hi-vis','Functional storage & branding'],color:'#87372d'},
 {id:'tactical',name:'Tactical Pro',type:'Industry',tag:'READY FOR THE MISSION',description:'Purposeful outerwear for demanding environments and operational teams.',features:['Tactical outerwear','Practical, professional design'],color:'#4a503e'},
 {id:'campus',name:'Campus Pro',type:'Teams',tag:'ONE CAMPUS. ONE IDENTITY.',description:'School pride, thoughtfully made. A smart look for students and campus leaders.',features:['Softshell · Bomber · Puffer','Crests, colours & personalisation'],color:'#233a57'},
 {id:'safari',name:'Safari Pro',type:'Outdoor',tag:'MADE FOR THE GREAT OUTDOORS',description:'Earthy tones and dependable comfort for guides, lodges and outdoor crews.',features:['Puffer · Parka · Bodywarmer','Plain, trimmed or wildlife print'],color:'#77704e'},
 {id:'sport',name:'Sport Pro',type:'Teams',tag:'ONE TEAM. ALL IN.',description:'From the touchline to the training ground. Wear your team identity with pride.',features:['Windbreaker · Bodywarmer','Team colours & sublimation'],color:'#51a7cf'},
 {id:'mining',name:'Mining Pro',type:'Industry',tag:'BUILT FOR THE SHIFT',description:'Work-focused outerwear with high-visibility options for industrial crews.',features:['Puffer · Parka · Softshell','Hi-vis & reflective options'],color:'#e79727'},
 {id:'healthcare',name:'Healthcare Pro',type:'Business',tag:'PROFESSIONAL. PROTECTED.',description:'Comfortable, coordinated jackets for the people who care for others.',features:['Softshell · Puffer · Parka','Names, roles & organisation logos'],color:'#26496f'},
] as const;
export type Collection = typeof collections[number];
export const whatsappNumber = (import.meta.env.VITE_WHATSAPP_NUMBER || '26775296591').replace(/\D/g,'');
export const sizes = ['XS','S','M','L','XL','XXL','XXXL','Custom'] as const;
export function whatsappUrl(message:string) { return whatsappNumber ? `https://wa.me/${whatsappNumber}?text=${encodeURIComponent(message)}` : `https://wa.me/?text=${encodeURIComponent(message)}`; }

export const inquiryMessage='Hello JD Jackets, I am interested in custom jackets for my business and would like to get more information.';
export const industries = [
 {id:'corporate',name:'Corporate & Office Teams',audience:'Employees, management teams, corporate events and company activities.',description:'Create a coordinated, professional appearance for your staff, from the office to client visits and company events.',teams:['Businesses and professional services','Office staff and management teams','Corporate events and associations'],focus:['Company colours and a consistent team appearance','Chest, back or sleeve branding','Puffer, softshell and parka options']},
 {id:'logistics',name:'Logistics & Transport',audience:'Delivery companies, fleet operators, warehouse staff and distribution teams.',description:'Branded outerwear for the people who keep your business moving, with practical details for busy working days.',teams:['Courier and delivery businesses','Fleet and transport operators','Warehouse and distribution teams'],focus:['Recognisable company branding','Practical pockets and comfortable movement','Softshell, fleece and high-visibility options']},
 {id:'tactical',name:'Security & Operational Teams',audience:'Security companies, patrol teams, supervisors and professional operational crews.',description:'Build a clear, consistent team identity for security and operational staff, with functional outerwear suited to their duties.',teams:['Private security companies','Patrol and site security teams','Operational supervisors and field crews'],focus:['Company logos, names and role identification','Practical features and fit for operational work','Materials and requirements agreed in your specification']},
 {id:'campus',name:'Schools & Education',audience:'Schools, colleges, universities, teachers, student groups and campus teams.',description:'Bring your school or institution’s identity to life with custom jackets in your colours, carrying your crest and team details.',teams:['Schools, colleges and universities','Teaching and campus staff','Student groups, clubs and school associations'],focus:['School crests and institution colours','Mixed sizes across staff and student groups','Softshell, bomber and puffer options']},
 {id:'safari',name:'Tourism & Hospitality',audience:'Lodges, hotels, safari guides, hospitality businesses and outdoor crews.',description:'Give guests a recognisable team to turn to. Create branded outerwear for guides, lodge staff and hospitality teams working indoors and out.',teams:['Safari lodges and tour operators','Hotels and hospitality businesses','Guides, outdoor crews and guest-facing staff'],focus:['A coordinated guest-facing team identity','Earth-tone palettes and your organisation’s logo','Puffer, parka and bodywarmer options']},
 {id:'sport',name:'Sports & Events',audience:'Sports clubs, coaches, training teams, event staff and associations.',description:'Put your club, event or association’s identity on show with team colours, sponsor branding and coordinated jackets for the whole group.',teams:['Sports clubs and coaching teams','Event organisers and staff','Associations and community organisations'],focus:['Team colours, names and sponsor logos','Plain, trimmed and sublimated designs','Windbreaker and bodywarmer options']},
 {id:'mining',name:'Construction, Mining & Engineering',audience:'Construction companies, engineers, site workers, maintenance teams and industrial crews.',description:'Custom work-focused jackets for companies working on site and in the field, with branding and practical features planned around your environment.',teams:['Construction and engineering companies','Mining and industrial workforces','Site supervisors, maintenance teams and field workers'],focus:['Company and role identification','High-visibility and reflective options','Fabric and performance needs reviewed for your work environment']},
 {id:'healthcare',name:'Healthcare & Care Teams',audience:'Clinics, hospitals, care organisations, support staff and outreach teams.',description:'Create a professional, coordinated look for the teams who care for others, with your organisation’s colours, names and roles.',teams:['Hospitals, clinics and medical practices','Care organisations and support teams','Community health and outreach teams'],focus:['Organisation logos, names and role branding','Comfortable, coordinated staff outerwear','Softshell, puffer and parka options']},
] as const;
export type Industry = typeof industries[number];
